<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
		<RootNamespace>$(Id)</RootNamespace>
		<LangVersion>8.0</LangVersion>
		<OutputPath>../build/</OutputPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Data.Tables" Version="$(AzureDataTablesVersion)" />
		<PackageReference Include="Azure.Storage.Blobs" Version="$(AzureStorageBlobsVersion)" />
	</ItemGroup>

</Project>
