<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
		<RootNamespace>DataAccess.AzureStorage</RootNamespace>
		<LangVersion>8.0</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Data.Tables" Version="12.10.0" />
		<PackageReference Include="Azure.Storage.Blobs" Version="12.21.2" />
	</ItemGroup>

</Project>
