# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: main-build CI

on:
  workflow_dispatch:  # This allows manual triggering
  push:
    branches:
      - master                      # Specific branch (master)
      - develop                     # Specific branch (develop)
      - 'feature/*'                 # Any branch that starts with 'feature/'
      - 'release/*'                 # Any branch that starts with 'release/'
  pull_request:
    branches:
      - master                      # Trigger on pull requests to the master branch
      - develop                     # Trigger on pull requests to the develop branch
      - 'feature/*'                 # PRs to feature branches
      - 'release/*'                 # PRs to release branches

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        solution: ['src/DataAccess.AzureStorage.sln']

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up .NET SDK (for .NET Standard 2.0 and .NET 8.0)
    - name: Set up .NET 8.0 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    # Install Visual Studio Build Tools (to build .NET Framework projects)
    - name: Install Visual Studio
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: '17.0'  # Visual Studio 2022

    # Restore .NET dependencies for .NET Standard and .NET Core projects
    - name: Restore .NET dependencies
      run: dotnet restore ${{ matrix.solution }}

    # Build .NET Standard and .NET Core projects (use dotnet build)
    - name: Build .NET Standard and .NET Core projects
      run: dotnet build ${{ matrix.solution }} --configuration Release --no-restore

    # Build .NET Framework project (use MSBuild)
    - name: Build .NET Framework project
      run: |
        msbuild src/AzureStorage.Dummy.Net481.MVC/AzureStorage.Dummy.Net481.MVC.csproj /p:Configuration=Release /p:Platform="Any CPU" /p:RestorePackages=false
    
